import Header from "@/components/header/Header";
import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Footer from "@/components/footer/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  viewport: "width=device-width,initial-scale=1",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="flex flex-col justify-between  gap-sub-medium relative min-h-screen">
        <Header
          height="h-[150px]"
          //top-[150px]
          textColor="text-neutral80"
          textType="sub-heading"
          logoColor="text-neutral80"
          logoType="heading--sub-large font-bold tracking-widest"
          mobileTextType="sub-heading"
        ></Header>
        {children}
        <Footer
          height="h-[100px]"
          bgColor="bg-black"
          flex="flex items-center justify-center"
        ></Footer>
      </body>
    </html>
  );
}
