import "@/app/globals.css";
import { Providers } from "@/components/darkMode/providers";

import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  viewport: "width=device-width,initial-scale=1",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="relative mb-sub-large flex min-h-screen flex-col gap-sub-large overflow-x-hidden bg-primary1 duration-medium dark:bg-primary99">
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
