import Header from "@/components/ui/header/Header";
import "@/app/globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import SearchBar from "@/components/ui/header/SearchBar";
import Button from "@/components/ui/button/Button";
import { getServerSession } from "next-auth";
import { authOptions } from "../api/auth/[...nextauth]/route";
import UserMenu from "@/components/user/UserMenu";

import LoginModal from "@/components/user/Login";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  viewport: "width=device-width,initial-scale=1",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <>
      <Header
        height="h-[100px] "
        //top-[100px]
        textColor="text-neutral80"
        textType="sub-heading"
        logoColor="text-neutral80 dark:text-primary10"
        logoType="heading font-bold tracking-widest"
        mobileTextType="sub-heading"
        bgColor="bg-primary10 border-b-4 border-neutral80 dark:border-primary20 dark:bg-primary90"
      ></Header>
      {children}
    </>
  );
}
